### ISSUE TITLE
CLEAN UP OUR CODE!

### ISSUE THREAD

**Issue by schineaj23** [Team2068/2022WCD#26]
Our code is getting messy, spaghetti and unreadable. 
now we must do a... r̵̢̡̡̲̯̥͉̤̟̝̝̹̞̹̯͉̉̽̿͂̓͑͝ę̸͍̪̩̳̘̞̗̻͈̫͓̗̘̺̘͖̬͋͆̀͑͋́́͌͌̓̒͆̾́̐͋̿͊͑̊͘̚͜f̴̡̨̢̡͈̦͚̪͎̤̼̥̬͇̣̱̞̥͔̟̖̱̗͈̼͔̣̩͖̬̌̀̒̓́̐́̔͌͊̌̈́͑̐͛͌͌͐̓̃̐̍̑́̐́̅͒̂̅̏̾̒͘̕͘͝a̷̢̡̩̼̘̠͔͕͗͜ͅc̷̡̧̨̨̡̧̢̡̛̪̟̞͔̝̲̟͎̳͚̻͈͈̤̰̣̺͈͇͓̝͉̗̗̮̥̠͐́̎̓͌̽̊͒̐̓͐̂̉͛͆͂̿̕ͅt̸̡̨̙͍̫̮͉͈͍͉̠̟̝͚̞̬̜͉̳̘͙̫͇̣̦̯̘̣̖̖̠͚͈̱̹̪̙̬̀̏̾͌̎̎̀̀̍̍̌͌̔̏̐̈́̓̍̅̅͋̏̀͋̉̈́ơ̵͓̫̅̊̓̏̀̆̂̂͒̅̎̒͛̽͐̉̂̂r̷̨̧̨̡̡̛͖̩͕̺̱̙̙̠̯̻̯̙͉̣̜̪̫̹͖̬͍͚̟̖̝̟͓̭͚̲̾͐̎̿̋̃̐̅̿̿͂̇́͒͗̈̽͊̏̐̽͒͑͜͝͠͠͠

Goals of this project:
- Adhere to Google Style convention
- Remove dead code
- Bugfix currently existing code
- Establish good and consistent practices

**Comment by keiraSchoolcraft** [comment]
Done #27
